### ISSUE TITLE
Doesn't work in chrome

### ISSUE THREAD

**Issue by jakefb** [y-js/shared-filesystem#1]
The shared-filesystem UI doesn't appear in chrome and I get this error in the console. Works fine in Firefox.

```
Uncaught SyntaxError: Unexpected token =>    shared-filesystem.html:174
```

I'm new to this project and haven't used shared-filesystem before. What could the problem be?

**Comment by dmonad** [comment]
I use [arrow functions](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Functions/Arrow_functions), a language feature that is not available in your browser. It is supported in chrome since chrome 45.

Usually I use Babel to crosscompile my code to ES5. But that's not really an option here, so I'm going to fix this. Thanks for the report
